//
//  ContainerValueExample.swift
//  AnySubviews
//
//  Created by Lumisilk on 2024/08/03.
//

import SwiftUI
import AnySubviews

struct ContainerValueExample: View {
    var body: some View {
        VStack {
            BackportGroup(subviews: content) { subviews in
                ForEach(subviews) { subview in
                    let _ = print( subview.containerValues[\.myValue] )
                    return subview
                }
            }
        }
    }
    
    var content: some View {
        Group {
            Text("Default")
            
            Text("1")
                .anyContainerValue(keyPath: \.myValue, 1)
        }
    }
}

// Generated By Macro
//extension AnyContainerValueKeys {
//    @AnyEntry var myValue = 0
//}

extension AnyContainerValueKeys {
    enum __Key_myValue: AnyContainerValueKey, ContainerValueKey {
        static var defaultValue: Int { 0 }
        
        @available(iOS 18.0, macOS 15.0, tvOS 18.0, watchOS 11.0, visionOS 2.0, *)
        static var containerKeyPath: WritableKeyPath<ContainerValues, Int> {
            \ContainerValues.delegate.myValue
        }
        
    }
    
    var myValue: __Key_myValue.Type {
        __Key_myValue.self
    }
}

#Preview {
    ContainerValueExample()
}
